"""multi-device session support

Revision ID: 487ccae20a48
Revises: f05f493d5808
Create Date: 2025-08-19 07:15:21.589321

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "487ccae20a48"
down_revision: Union[str, None] = "f05f493d5808"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		"devices",
		sa.Column("id", sa.UUID(), nullable=False),
		sa.Column("user_id", sa.UUID(), nullable=False),
		sa.Column("device_type", sa.String(length=50), nullable=False),
		sa.Column("device_name", sa.String(length=50), nullable=False),
		sa.Column("os_version", sa.String(length=50), nullable=False),
		sa.Column("push_token", sa.String(length=100), nullable=False),
		sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
		sa.Column("is_deleted", sa.Boolean(), default=False, nullable=False),
		sa.Column("deleted_at", sa.DateTime(), nullable=True),
		sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
		sa.PrimaryKeyConstraint("id"),
	)
	op.create_index(op.f("ix_devices_user_id"), "devices", ["user_id"], unique=False)
	op.create_table(
		"sessioneventlogs",
		sa.Column("id", sa.UUID(), nullable=False),
		sa.Column("user_id", sa.UUID(), nullable=False),
		sa.Column("device_id", sa.UUID(), nullable=False),
		sa.Column(
			"event",
			sa.Enum("signin", "signup", "sign_out", "token_refresh", name="session_event_enum"),
			nullable=False,
		),
		sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
		sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
		sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
		sa.PrimaryKeyConstraint("id"),
	)
	op.create_index(
		op.f("ix_sessioneventlogs_device_id"),
		"sessioneventlogs",
		["device_id"],
		unique=False,
	)
	op.create_index(
		op.f("ix_sessioneventlogs_user_id"), "sessioneventlogs", ["user_id"], unique=False
	)
	op.create_table(
		"sessions",
		sa.Column("id", sa.UUID(), nullable=False),
		sa.Column("user_id", sa.UUID(), nullable=False),
		sa.Column("device_id", sa.UUID(), nullable=False),
		sa.Column("refresh_token", sa.Text(), nullable=False),
		sa.Column("expires_at", sa.DateTime(), nullable=False),
		# sa.Column('is_active', sa.Boolean(), default=True, nullable=False),
		sa.Column(
			"last_activity",
			sa.DateTime(),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
		sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
		sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
		sa.PrimaryKeyConstraint("id"),
		sa.UniqueConstraint("user_id", "device_id", name="uq_user_device"),
	)
	op.create_index(op.f("ix_sessions_device_id"), "sessions", ["device_id"], unique=False)
	op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
	op.drop_constraint("users_id_key", "users", type_="unique")
	op.drop_constraint("users_phone_key", "users", type_="unique")
	op.create_index(op.f("ix_users_id"), "users", ["id"], unique=True)
	op.create_index(op.f("ix_users_phone"), "users", ["phone"], unique=True)
	# ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_index(op.f("ix_users_phone"), table_name="users")
	op.drop_index(op.f("ix_users_id"), table_name="users")
	op.create_unique_constraint("users_phone_key", "users", ["phone"])
	op.create_unique_constraint("users_id_key", "users", ["id"])
	op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
	op.drop_index(op.f("ix_sessions_device_id"), table_name="sessions")
	op.drop_table("sessions")
	op.drop_index(op.f("ix_sessioneventlogs_user_id"), table_name="sessioneventlogs")
	op.drop_index(op.f("ix_sessioneventlogs_device_id"), table_name="sessioneventlogs")
	op.drop_table("sessioneventlogs")
	op.drop_index(op.f("ix_devices_user_id"), table_name="devices")
	op.drop_table("devices")
	sa.Enum(name="session_event_enum").drop(op.get_bind(), checkfirst=True)
	# ### end Alembic commands ###
