"""Initial

Revision ID: f05f493d5808
Revises:
Create Date: 2025-08-12 09:51:56.010018

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f05f493d5808"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		"outboxevents",
		sa.Column("id", sa.UUID(), nullable=False),
		sa.Column("topic", sa.String(length=100), nullable=False),
		sa.Column("payload", sa.JSON(), nullable=False),
		sa.Column(
			"status",
			sa.Enum("not_processed", "processing", "processed", name="event_status_enum"),
			server_default=sa.text("'not_processed'"),
			nullable=False,
		),
		sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
		sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
		sa.PrimaryKeyConstraint("id"),
	)
	op.create_table(
		"users",
		sa.Column("id", sa.UUID(), nullable=False),
		sa.Column("phone", sa.String(length=11), nullable=False),
		sa.Column("created_at", sa.DateTime(), nullable=False),
		sa.Column("is_active", sa.Boolean(), nullable=False),
		sa.PrimaryKeyConstraint("id"),
		sa.UniqueConstraint("id"),
		sa.UniqueConstraint("phone"),
	)
	op.create_table(
		"userstatushistorys",
		sa.Column("id", sa.UUID(), nullable=False),
		sa.Column("user_id", sa.UUID(), nullable=False),
		sa.Column(
			"status",
			sa.Enum("activated", "deactivated", name="user_status_enum"),
			nullable=False,
		),
		sa.Column("timestamp", sa.DateTime(), nullable=False),
		sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
		sa.PrimaryKeyConstraint("id"),
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_table("userstatushistorys")
	op.drop_table("users")
	op.drop_table("outboxevents")
	# ### end Alembic commands ###
